<?php

// $Id$

/**
 * @file
 *  Link general privatemsg module functionalities to services module.
 */
/**
 * Implementation of hook_perm().
 */

function privatemsg_services_permission() {
  return array(
    'get private messages from remote'  => array(
      'title'       => t('Load remote private messages'),
      'description' => t('View messages via services'),
    ),
    'send private messages from remote' => array(
      'title'       => t('Send remote private messages'),
      'description' => t('Write messages via services'),
    ),
  );
}

/**
 * Implementation of hook_service().
 */

function privatemsg_services_services_resources() {
  return array(
    'privatemsg' => array(
      'index'    => array(
        'file'                 => array(
          'type'   => 'inc',
          'module' => 'privatemsg_services',
          'name'   => 'privatemsg_services'
        ),
        'callback'             => 'privatemsg_services_get',
        'access callback'      => 'privatemsg_services_access',
        'access callback file' => array(
          'type'   => 'inc',
          'module' => 'privatemsg_services',
          'name'   => 'privatemsg_services'
        ),
        'args'                 => array(),
      ),
      'retrieve' => array(
        'callback'         => 'privatemsg_services_get_thread',
        'access arguments' => array(
          'get private messages from remote'
        ),
        'file'             => array(
          'type'   => 'inc',
          'module' => 'privatemsg_services',
          'name'   => 'privatemsg_services'
        ),
        'args'             => array(
          array(
            'name'        => 'thread_id',
            'type'        => 'int',
            'description' => t(
              'The ID of the thread that should be retrieved.'
            ),
            'source'      => array(
              'path' => 0
            ),
          ),
        ),
      ),
      'create'   => array(
        'callback'         => 'privatemsg_services_send',
        'access arguments' => array(
          'send private messages from remote'
        ),
        'file'             => array(
          'type'   => 'inc',
          'module' => 'privatemsg_services',
          'name'   => 'privatemsg_services'
        ),
        'args'             => array(
          array(
            'name'        => 'message',
            'type'        => 'array',
            'description' => t('A privatemsg array'),
            'source'      => 'data',
          ),
        ),
        'help'             => t(
          'Returns TRUE if the message sending was a success.'
        )
      ),
    ),
  );
}
